name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            ~/.cache/coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

      - name: Scalafmt Check All
        run: sbt +scalafmtCheckAll

  sonar:
    runs-on: ubuntu-latest
    needs: [linter]
    timeout-minutes: 25
    env:
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            ~/.cache/coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

      - run: sbt -Dsonar.login=${{ secrets.SONAR_TOKEN }} sonar

  labeler:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    timeout-minutes: 1
    steps:
      - name: Label the PR action
        continue-on-error: true
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}

  release_draft:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
