name: release-drafter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release_draft:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
